# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('brd_date', models.DateField()),
                ('ticket', models.IntegerField()),
                ('is_head', models.BooleanField()),
                ('i_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Group')),
            ],
        ),
    ]
