# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_student_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(default=30500),
            preserve_default=False,
        ),
    ]
