# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_student_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='brd_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(null=True),
        ),
    ]
