# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20161214_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
