# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20161227_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='webapp.Group'),
        ),
    ]
